### ISSUE TITLE
HTTP Thread not dying when server shutdowns 

### ISSUE THREAD

**Issue by Dev0Louis** [NickImpact/Impactor#5]
![image](https://github.com/NickImpact/Impactor/assets/82884007/87438ad9-babb-4329-b413-4ed71ddfcb68)
This thread stays alive when the server shutdown is finished causing the java process to stay alive.

**Comment by NickImpact** [comment]
What version of the plugin are you using?

**Comment by NickImpact** [comment]
Closing this as no comment has been made and I assume this is using 5.0.0, before the OkHttp library was upgraded to accommodate this problem
