### ISSUE TITLE
Target Selectors

### ISSUE THREAD

**Issue by atrustyfox** [NickImpact/Impactor#6]
There is no ability to add a target selector currently in the economy portion of the "mod". How would I target a specific user to pay them currency through a command? Something such as $user, or @p even is not supported. I can select the user's username, but I want to run this, say from a command block for ANY interacting user. 

Can this be achieved?

**Comment by NickImpact** [comment]
Should certainly be doable, just need to add support to the command interpreter to allow for such. Didn't initially envision much wider support beyond how it is now as Impactor's backend service was designed namely to be a simple solution until another plugin overrode the implementation for its own using the API.

Something like such should be easy enough to add.

**Comment by NickImpact** [comment]
Support for @r (Random Target) and @s (Command Source) are now available. This doesn't support filters that you can normally apply to the selectors. Ideally this will get better compatibility in the future but this will be how it is for now.
