### ISSUE TITLE
money

### ISSUE THREAD

**Issue by ghost** [NickImpact/Impactor#9]
Way to add money for players

**Comment by ojcastillo29** [comment]
Please be a lot more specific in your use case. There is a deposit command and you are able to pull from a "Server" created account and utilize the pay command(s), to fulfill server to player payments.

**Comment by NickImpact** [comment]
Closing due to lack of details on request, and "requested" functionality fully capable through multiple methods already.

**Comment by ghost** [comment]
i couldnt ever get the methods you mentied to work i was suggesting a command. /economy add {player} {ammount}
or  /economy set {player} {ammount}

**Comment by NickImpact** [comment]
Set exists, add = deposit. Flip amount and player. See /impactor help and make sure you have permissions to use those commands
